### ISSUE TITLE
Is the dataset too simple?

### ISSUE THREAD

**Issue by ShengleiH** [google-research-datasets/MAVE#3]
Hi, thanks for your great works!

After reading your paper, I found the baseline of this dataset on all attribtues has achieved 98.34 on F1. Does it means that this dataset is too simple as a benchmark in attribute value extraction task?

**Comment by liyang2019** [comment]
Yes, the dataset is simple under random splitting. However, as explained in the paper, the dataset can be used for studying zero-shot/few-shot learning, e.g. Figure 6, which is still an open question in the literature.

The reason for being simple under random splitting could be due to the following reasons:

1. We used an ensemble of models trained on a large amount of data to generate labels. These labels are later heavily filtered by a set of human curated rules to ensure a high quality. After this filtering, together with the fact that there are still many examples, the dataset could become simple for random splitting.
2. The ensemble of models we used to generate the labels are also in Transformer architecture, so the final labels might have some biases towards the Transformer architecture.

Hope the above explanation helps.

Thanks!

**Comment by ccclyu** [comment]
I have the same concern as mentioned from @ShengleiH. After the strict human filtering, have you randomly sample some examples to manually evaluate the quality (seem not reported in the paper)? Another question is how to use MAVE to benchmarking  the attribute extraction methods given the random-sampled dataset is a bit simple. Suggestions would be greatly appreictaed !

**Comment by liyang2019** [comment]
We sampled 1k annotations and manually examined by two people, and the precision we obtained is 97.8%. So we believe the open sourced dataset is of high quality. We briefly mentioned this in the second to the last paragraph in the introduction section. 

Given the random split of the whole dataset is relatively simple for transformer models, I think the following benchmarks could be more meaningful:

1. The full dataset contains a large number of attributes (3M), so only using a downsampled subset for training and evaluation could make the dataset harder.
2. Zero-shot or few-shot learning benchmarks by holding out a subset of attributes. Similar to studies such as in the GPT-3 and transformer for vision works.

Hope those will be helpful.

Thanks!
