### ISSUE TITLE
Product Images

### ISSUE THREAD

**Issue by joshmyersdean** [google-research-datasets/MAVE#5]
Hello!

Thank you for this work. I was wondering if you have a script to download the images for the products as well?

**Comment by liyang2019** [comment]
We currently don't have a script to download the images for the products, since this work only focus on text features. 

Wondering are you referring the images in the Amazon Review Dataset? I think the simplest way to download images is to modify `clean_amazon_product_metadata_main.py ` to also download images from "imageURL" or "imageURLHighRes" from the product meta data. We have checked the 'asin' number is an unique identifier for texts features of the product meta data, but we haven't checked whether it is a unique identifier when also including image urls.

**Comment by joshmyersdean** [comment]
Thank you so much, I will give that shot!
